export class AppRoutes {
  static readonly INDEX: string = 'pages/Index';
  static readonly LOGIN: string = 'pages/LoginPage';
  static readonly REGISTER: string = 'pages/RegisterPage';
  static readonly HOME: string = 'pages/GreenhouseHomePage';
  static readonly MANAGE: string = 'pages/ManagePage';
  static readonly MINE: string = 'pages/MinePage';
  static readonly SETTINGS: string = 'pages/SettingsPage';
  static readonly DEVICE_MANAGE: string = 'pages/DeviceManagePage';
  static readonly DEVICE_MONITOR: string = 'pages/DeviceMonitorPage';
  static readonly GREENHOUSE_LIST: string = 'pages/GreenhouseListPage';
  static readonly ADD_GREENHOUSE: string = 'pages/AddGreenhousePage';
  static readonly ALARM_RECORD: string = 'pages/AlarmRecordPage';
  static readonly ALARM_DETAIL: string = 'pages/AlarmDetailPage';
  static readonly ALARM_HANDLE: string = 'pages/AlarmHandlePage';
  static readonly ALARM_THRESHOLD: string = 'pages/AlarmThresholdPage';
  static readonly REALTIME_ANALYSIS: string = 'pages/RealTimeAnalysisPage';
  static readonly HISTORY_ANALYSIS: string = 'pages/HistoryAnalysisPage';
  static readonly VIDEO: string = 'pages/VideoPage';
  static readonly AI: string = 'pages/AiSuggestionPage';
  static readonly FEEDBACK: string = 'pages/FeedbackPage';
  static readonly EDIT_PROFILE: string = 'pages/EditProfilePage';
  static readonly NEW_PASSWORD: string = 'pages/NewPasswordPage';
}
