import { http } from './http'

export const fetchOverview = (greenhouseId) => http.get('/greenhouses/overview', { params: { greenhouseId } })
export const fetchAnalytics = (greenhouseId) => http.get('/greenhouses/analytics', { params: { greenhouseId } })
export const fetchGreenhouses = () => http.get('/greenhouses')
export const createGreenhouse = (payload) => http.post('/greenhouses', payload)
export const updateGreenhouse = (id, payload) => http.put(`/greenhouses/${id}`, payload)
export const deleteGreenhouse = (id) => http.delete(`/greenhouses/${id}`)
export const fetchDevices = (greenhouseId) => http.get('/greenhouses/devices', { params: { greenhouseId } })
export const createDevice = (payload) => http.post('/greenhouses/devices', payload)
export const updateDevice = (id, payload) => http.put(`/greenhouses/devices/${id}`, payload)
export const deleteDevice = (id) => http.delete(`/greenhouses/devices/${id}`)
export const fetchAlerts = (greenhouseId) => http.get('/greenhouses/alerts', { params: { greenhouseId } })
export const fetchAlertDetails = (greenhouseId) => http.get('/greenhouses/alerts/detail', { params: { greenhouseId } })
export const handleAlert = (id, payload) => http.post(`/greenhouses/alerts/${id}/handle`, payload)
export const alertCommand = (id, payload) => http.post(`/greenhouses/alerts/${id}/command`, payload)
export const fetchTraceability = (greenhouseId) => http.get('/greenhouses/traceability', { params: { greenhouseId } })
export const fetchBatches = (params) => http.get('/greenhouses/batches', { params })
export const fetchBatchDetail = (id) => http.get(`/greenhouses/batches/${id}`)
export const createBatch = (payload) => http.post('/greenhouses/batches', payload)
export const createBatchEvent = (id, payload) => http.post(`/greenhouses/batches/${id}/events`, payload)
export const sendDeviceCommand = (payload) => http.post('/greenhouses/devices/commands', payload)
